approvals:
  minimum: 1
commit:
  message:
    patterns: # commit message has to match any one of
      - "^#[0-9]+"       # starts with hash and digits (github issues)
X-Zalando-Team: "foundation"
X-Zalando-Type: tools
